name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Install GNU Radio
      run: |
        sudo apt-get update
        sudo apt-get install -y gnuradio gnuradio-dev libgnuradio-qtgui* python3-pyqt5
        apt-cache search pyqt5 | grep -i gui
        apt-cache search gnuradio | grep qtgui
        dpkg -l | grep gnuradio
  
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
  
    - name: Run tests
      run: |
        python3 -m unittest discover -s tests
