name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install GNU Radio
      run: sudo apt-get install -y gnuradio

    - name: Install PyQt5
      run: sudo apt-get install -y python3-pyqt5
    
    - name: Install GNU Radio with Qt GUI support
      run: |
        sudo apt-get update
        sudo apt-get install -y gnuradio gnuradio-dev python3-gnuradio python3-gnuradio-qtgui
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Make system packages available to Python 3.8
      run: |  
        SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
        echo "/usr/lib/python3/dist-packages" > "$SITE_PACKAGES/gnuradio.pth"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PyQt5

    - name: Run tests
      run: |
        python3 -m unittest discover -s tests
